config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :exchanges
  root 'exchanges#index'

  namespace :api do
    namespace :v1 do
      resources :historical_rates do
        resources :rates
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  validates_presence_of :target_currency,
                        :base_currency
  validates :amount, inclusion: { in: 1..100000000,
                                  message: "The amount can be between 1 and 100000000" }

  validates :waiting_time, inclusion: { in: 1..250,
                                        message: "The amount must be between 1 and 250" }


end

app/models/historical_rate.rb
class HistoricalRate < ApplicationRecord
  has_one :rate
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :historical_rate
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :exchanges
end

app/controllers/api/v1/historical_rates_controller.rb
class Api
  class V1
    class HistoricalRatesController < ApplicationController
      before_action :set_historical_rate

      def show; end

      private

      def set_historical_rate
        @rate = HistoricalRate.find(params[:id])
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_exchange, only: %i[edit update destroy show]

  def index
    @exchanges = Exchange.all
  end

  def new
    @exchange = Exchange.new
  end

  def create
    @exchange = current_user.exchanges.build(exchange_params)
    if @exchange.save
      redirect_to @exchange
    else
      render 'new'
    end
  end

  def show
    @exchange_order = Prediction.new(@exchange.amount,
                                     @exchange.base_currency,
                                     @exchange.target_currency,
                                     @exchange.waiting_time)
    @predictions = @exchange_order.final_prediction
    @top_three = @predictions.group_by { |item| item[:amount] }
                             .sort_by  { |key, _value| -key }
                             .first(3)
                             .map(&:last)
                             .flatten
  end

  def edit; end

  def update
    if @exchange.update(exchange_params)
      redirect_to @exchange
    else
      render 'edit'
    end
  end

  def destroy
    @exchange.destroy
    redirect_to exchanges_path
  end

  private

  def exchange_params
    params.require(:exchange)
          .permit(:amount,
                  :base_currency,
                  :target_currency,
                  :waiting_time,
                  :user_id)
  end

  def find_exchange
    @exchange = current_user.exchanges.find(params[:id])
  end
end

app/views/exchanges/_form.html.erb
<%= simple_form_for @exchange do |f| %>
  <%= f.input :amount,
              label: 'What amount would you like to exchange?',
              required: true,
              input_html: { min: 1} %>
  <%= f.input :base_currency,
              selected: [ "EUR" ],
              collection: ["EUR","AUD","CAD","CHF","CZK","DKK",
                           "GBP","HKD","HUF","JPY","KRW","NOK",
                           "NZD","PLN","SEK","SGD","USD","ZAR"],
              required: true %>
  <%= f.input :target_currency,
              selected: [ "USD" ],
              collection: ["EUR","AUD","CAD","CHF","CZK","DKK",
                           "GBP","HKD","HUF","JPY","KRW","NOK",
                           "NZD","PLN","SEK","SGD","USD","ZAR"],
              required: true %>
  <%= f.input :waiting_time,
              label: 'How many weeks would you like to wait?',
              required: true,
              hint: "Maximum 250 weeks",
              input_html: { min: 1, max: 250 }%>
  <%= f.button :submit %>
<% end %>

app/views/exchanges/edit.html.erb
<h1>Edit this Exchange</h1>

<%= render 'form' %>


<%= link_to 'Delete Exchange', exchange_path(@exchange), method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/exchanges/index.html.erb
<div class="container">
  <div class="jumbotron main-page">
    <h1 class="display-3">Exchangify</h1>
    <p class="lead">Welcome to the exchange world where money never sleeps.</p>
    <hr class="my-4">
    <p>Predict the future of the exchange rate you desire.</p>
    <p class="lead">
      <%= link_to "Create a new exchange", new_exchange_path, class: 'btn btn-primary btn-lg' %>
    </p>
  </div>
  <% if current_user.exchanges.count > 0 %>
  <div class="jumbotron main-page">
    <h2 class="display-4">Your exchanges</h2>
    <table class="table">
    <thead>
      <tr>
        <th>Amount / Currency</th>
        <th>Target Currency</th>
        <th>Start Date</th>
      </tr>
      </thead>
      <% @exchanges.each do |f| %>
        <% if f.user_id == current_user.id %>
          <tbody>
            <tr>
              <td scope="row"><%="#{f.amount} #{f.base_currency}"%></td>
              <td><%= f.target_currency %></td>
              <td><%= f.created_at.to_datetime.strftime("%Y-%m-%d") %></td>
              <td><%= link_to "View", exchange_path(f), class: "btn btn-success" %></td>
              <td><%= link_to "Edit", edit_exchange_path(f), class: "btn btn-info" %></li>
              <td><%= link_to "Delete", exchange_path(f), method: :delete, class: "btn btn-danger" %></td>
            </tr>
          </tbody>
        <% end %>
      <% end %>
    </table>
  </div>
  <% end %>

app/views/exchanges/new.html.erb
<div class="container" id="new-exchange">
  <h1>Start a new exhange</h1>

  <%= render 'form' %>
</div>

app/views/exchanges/show.html.erb
<%= link_to "Main Page",
            exchanges_path,
            class: 'btn btn-info btn-lg btn-block fixed-top' %>

<div class="jumbotron">

  <h2> Results for Exchange </h2>
  <h3> Date: <%= @exchange.created_at.strftime("%Y-%m-%d") %></h3>
  <h3> <%= "From #{@exchange.base_currency} to #{@exchange.target_currency}" %></h3>
  <%= line_chart @predictions.pluck(:date,:rate) %>

  <% if @predictions.length > 3 %>
  <h3>Top 3 dates to make the exchange</h3>
  <table class="table">
    <thead class="thead-default">
      <tr>
        <th>Week</th>
        <th>1 <%= @exchange.base_currency %></th>
        <th><%= "#{@exchange.amount} #{@exchange.base_currency}" %></th>
      </tr>
    </thead>
    <% @top_three.each do |prediction| %>
    <tbody>
      <tr class="table-success">
        <th scope="row"> <%= prediction[:date] - 1.week %> till <%= prediction[:date] %> </th>
        <td><%= "#{prediction[:rate].round(4)} #{@exchange.target_currency}" %></td>
        <td><%= prediction[:amount].round(2)  %> <%= @exchange.target_currency %></td>
      </tr>
      </tr>
    </tbody>
    <% end %>
  </table>
  <% end %>
  <h3>All dates and rates</h3>
  <table class="table">
    <thead class="thead-default">
      <tr>
        <th>Week</th>
        <th>1 <%= @exchange.base_currency %></th>
        <th><%= "#{@exchange.amount} #{@exchange.base_currency}" %></th>
      </tr>
    </thead>
    <% @predictions.each do |prediction| %>
    <tbody>
      <tr>
        <th scope="row"> <%= prediction[:date] - 1.week %> till <%= prediction[:date] %> </th>
        <td><%= "#{prediction[:rate].round(4)} #{@exchange.target_currency}" %></td>
        <td><%= prediction[:amount].round(2)  %> <%= @exchange.target_currency %></td>
      </tr>
      </tr>
    </tbody>
    <% end %>
  </table>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Converter</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= javascript_include_tag 'application', 'Chart.bundle', 'chartkick', 'data-turbolinks-track': 'reload' %>

    <div class="container">
      <%= yield %>
    </div>
    <% if user_signed_in? %>
      <%= link_to "Logout",
          destroy_user_session_path,
          method: :delete, class: 'btn btn-danger btn-lg btn-block fixed-bottom' %>
    <% end %>

  </body>
</html>